packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  bcrypt: true
  es5-ext: true
  prisma: true
  puppeteer: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - bcrypt
  - es5-ext
  - esbuild
  - prisma
  - puppeteer
  - sharp
  - unrs-resolver
